### ISSUE TITLE
Binds not working

### ISSUE THREAD

**Issue by MrEvilGamer** [qbcore-framework/qb-commandbinding#12]
In the latest core the binds are not working. Even if you try to do like any command it says. "No access to this command."
![unknown](https://user-images.githubusercontent.com/84228628/161424764-6f0caad6-0ce5-457e-a8de-8fd1b9973e71.png)

**Comment by sol-fitzy** [comment]
Did you create a thread in the QBCore Discord?

**Comment by sol-fitzy** [comment]
I see what you mean, doesn't seem to be allowing me to do any commands whatsoever.

**Comment by DisguisedOG** [comment]
Having the same issue since rebuilding from a qbcore just two days ago due to other reasons, maybe an update has caused this? I can't seem to fix it. I'm a newbie

**Comment by sol-fitzy** [comment]
I fixed this problem by doing some research,

**Grant the group permissions**
`add_ace qbcore.god command allow # Allow all commands`

**Make sure you are doing your inheritance for your groups**
`add_principal qbcore.god group.admin # God needs perms from admin`
`add_principal qbcore.god qbcore.admin # Allow gods access to admin commands`
`add_principal qbcore.admin qbcore.mod # Allow admins access to mod commands`

**Finally, add your perms**
`add_principal identifier.text:numbers qbcore.god #nameofgodperson`

If you have a resource that grants permission, make sure it is granting **qbcore.god** instead of **group.god**

**Comment by MrEvilGamer** [comment]
nope that does not fix it

**Comment by CodeRedDev** [comment]
This can be a lil tricky. E.g. if the command `car` is bound to `admin` permissions and you are part of the `qbcore.mod` group you won't have access to it even if you add the ace to the `qbcore.mod` group like this:

```cfg
add_ace qbcore.mod command.car allow
```

That is because `QBCore:CallCommand` checks for the ace of `admin` and not for the ace of `command.car`.

I fixed this for me by changing the permission check to the following in `QBCore:CallCommand` and adding the commands with `add_ace` to my specific administration groups.

```lua
local hasPerm = QBCore.Functions.HasPermission(src, "command."..QBCore.Commands.List[command].name)
```

**Comment by GhzGarage** [comment]
I've PR'd and tested this, thanks red
